LukeCurtie/-MagicMon

Gemfile, Gemfile.lock, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/schema.rb
Have this far started the alerts for devise
=> started devise

db/migrate/20240304121640_add_name_and_owner_to_user.rb, db/schema.rb
=> AddNameAndOwnerToUser

app/models/animal.rb, app/models/user.rb, db/migrate/20240304124028_create_animals.rb, db/schema.rb, test/models/animal_test.rb
=> AnimalModel

app/controllers/animals_controller.rb, app/views/animals/index.html.erb, app/views/animals/show.html.erb, app/views/layouts/application.html.erb, config/routes.rb, db/seeds.rb, test/controllers/animals_controller_test.rb
=> AnimalController

.gitignore
=> creation of a booking branch

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/create.html.erb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, config/routes.rb, db/migrate/20240305082657_create_bookings.rb, db/schema.rb, test/controllers/bookings_controller_test.rb, test/models/booking_test.rb
creation of booking model and controller
=> creation of booking model and controller

app/views/animals/index.html.erb, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
=> The first footer push

.gitignore, app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/animals/index.html.erb, app/views/bookings/create.html.erb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, config/routes.rb, db/migrate/20240305082657_create_bookings.rb, db/schema.rb, test/controllers/bookings_controller_test.rb, test/models/booking_test.rb
=> Animals view

app/controllers/animals_controller.rb, app/views/animals/index.html.erb
=> added to controller

app/views/animals/new.html.erb
Have added a model commented out, for abilities
=> added model for ability

app/controllers/animals_controller.rb, app/javascript/application.js, app/views/animals/edit.html.erb, app/views/animals/index.html.erb, app/views/animals/new.html.erb, app/views/animals/show.html.erb
=> finished edit

app/models/animal.rb, app/views/animals/edit.html.erb
=> validations

app/controllers/animals_controller.rb, app/controllers/application_controller.rb
=> Authenticate

app/controllers/bookings_controller.rb, app/views/bookings/index.html.erb, config/routes.rb
=> BookingPath

app/controllers/animals_controller.rb
=> controller

app/assets/stylesheets/components/_abilities.scss, app/assets/stylesheets/components/_index.scss, app/views/animal_abilities/new.html.erb
=> abitieschanging

app/controllers/animals_controller.rb, app/views/animals/my_animals.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
=> BookingRequests

app/controllers/bookings_controller.rb, app/views/bookings/my_bookings.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
=> MyBookings

app/assets/stylesheets/components/_animal_card.scss, app/assets/stylesheets/components/_card_image.scss, app/views/animals/my_animals.html.erb, app/views/animals/show.html.erb
=> buttonlink

app/controllers/animals_controller.rb, app/controllers/bookings_controller.rb, app/javascript/controllers/datepicker_controller.js, app/views/animals/_book_form.html.erb, app/views/bookings/my_bookings.html.erb, app/views/shared/_navbar.html.erb
=> added duration
